animatedcollapse.addDiv('dok1', 'fade=0, hide=1, group=doku')
animatedcollapse.addDiv('dok2', 'fade=0, hide=1, group=doku')
animatedcollapse.addDiv('dok3', 'fade=0, hide=1, group=doku')
animatedcollapse.addDiv('dok4', 'fade=0, hide=1, group=doku')
animatedcollapse.addDiv('dok5', 'fade=0, hide=1, group=doku')
animatedcollapse.addDiv('dok6', 'fade=0, hide=1, group=doku')
animatedcollapse.addDiv('dok7', 'fade=0, hide=1, group=doku')
animatedcollapse.addDiv('dok8', 'fade=0, hide=1, group=doku')
animatedcollapse.addDiv('dok9', 'fade=0, hide=1, group=doku')
animatedcollapse.addDiv('dok10', 'fade=0, hide=1, group=doku')
animatedcollapse.addDiv('doka', 'fade=0, hide=1')
animatedcollapse.addDiv('dokb', 'fade=0, hide=1')
animatedcollapse.addDiv('dokc', 'fade=0, hide=1')
animatedcollapse.addDiv('dokd', 'fade=0, hide=1')
animatedcollapse.addDiv('doke', 'fade=0, hide=1')
animatedcollapse.addDiv('dokvisiblea', 'fade=0, hide=0, group=visible')
animatedcollapse.addDiv('dokvisibleb', 'fade=0, hide=1, group=visible')
animatedcollapse.ontoggle=function($, divobj, state){}
animatedcollapse.init()